# Generated by Django 6.1 on 2026-10-05 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de dispositivo',
                'verbose_name_plural': 'Categorías de dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('serial_code', models.CharField(max_length=50, unique=True, verbose_name='Código de serie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.zone', verbose_name='Zona')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('consumption_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo (kWh)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Lectura de consumo',
                'verbose_name_plural': 'Lecturas de consumo',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(verbose_name='Fecha de mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='devices.device', verbose_name='Dispositivo')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='accounts.userprofile', verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Registro de mantenimiento',
                'verbose_name_plural': 'Registros de mantenimiento',
                'ordering': ['-performed_at'],
            },
        ),
    ]
