# Generated by Django 6.1 on 2026-10-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetcode'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='jefatura',
            new_name='head',
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to='accounts.userprofile', verbose_name='Jefatura'),
        ),
    ]
