# Generated by Django 6.1 on 2026-10-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_department_jefatura_department_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='organizations.department', verbose_name='Departamento'),
        ),
    ]
