# Generated by Django 6.1 on 2026-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='evidence',
            field=models.ImageField(blank=True, upload_to='incidencias/%Y/%m/'),
        ),
    ]
