# Generated by Django 6.1 on 2026-10-01 15:54

import incidents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidencia_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='evidence',
            field=models.ImageField(blank=True, upload_to='incidencias/%Y/%m/', validators=[incidents.validators.validate_evidence_file]),
        ),
    ]
