# Generated by Django 6.1 on 2026-10-01 16:35

import django.db.models.deletion
import incidents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('incidents', '0003_alter_incidencia_evidence'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='evidence',
            field=models.ImageField(blank=True, upload_to='incidencias/%Y/%m/', validators=[incidents.validators.validate_evidence_file], verbose_name='Evidencia'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_reportadas', to='accounts.userprofile', verbose_name='Reportado por'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='status',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta')], default='ABIERTA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='organizations.zone', verbose_name='Zona'),
        ),
    ]
