# Generated by Django 6.1 on 2026-10-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_rename_models_to_english'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AlterModelOptions(
            name='incidentfollowup',
            options={'verbose_name': 'Seguimiento de incidencia', 'verbose_name_plural': 'Seguimientos de incidencia'},
        ),
    ]
