# Generated by Django 6.1 on 2026-10-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetcode'),
        ('incidents', '0006_alter_incident_options_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to='accounts.userprofile', verbose_name='Reportado por'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='organizations.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='incidentfollowup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_followups', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='incidentfollowup',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='incidents.incident'),
        ),
    ]
