# Generated by Django 6.1 on 2026-10-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_department_and_more'),
        ('incidents', '0007_alter_incident_reported_by_alter_incident_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentfollowup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_followups', to='accounts.userprofile', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='incidentfollowup',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='incidents.incident', verbose_name='Incidencia'),
        ),
        migrations.AlterField(
            model_name='incidentfollowup',
            name='note',
            field=models.TextField(verbose_name='Nota'),
        ),
    ]
